name: js_dependencies_tools
description: Analyzer-powered dependency tooling
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  analyzer: ^8.4.0
  path: ^1.9.0
executables:
  dart_dependency: dart_dependency
